# Generated by Django 5.2.3 on 2026-03-06 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.SlugField(primary_key=True, serialize=False),
        ),
    ]
