# Generated by Django 5.2.3 on 2026-03-06 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='duration',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
