# Generated by Django 5.2.3 on 2026-03-08 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_course_category_alter_course_thumbnail_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
        migrations.AddField(
            model_name='payment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Price at time of purchase', max_digits=10),
            preserve_default=False,
        ),
    ]
