# Generated by Django 5.2.3 on 2026-03-31 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_payment_coupon'),
        ('myapp', '0015_alter_category_options_and_more'),
    ]

    operations = [
    ]
