# Generated by Django 5.2.3 on 2026-03-31 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_merge_20260331_1648'),
    ]

    operations = [
        migrations.DeleteModel(
            name='review',
        ),
    ]
